.github/PULL_REQUEST_TEMPLATE.md

*note that this is going into master directly*

add github pr template

---

.travis.yml
ci/requirements-3.5.yml
docs/installing.rst

test metsim with python 3.5 on travis

---

README.md

add table to readme with badges and links

---

metsim/physics.py

Removing caching of solar_geom.  Fixes #60.

---

metsim/metsim.py

- closes #72 
- spatially subsets along lat/lon dimensions to ensure that data read from daily input forcings match the domain

spatially subset daily netcdf to match domain

---

metsim/io.py
metsim/methods/mtclim.py
metsim/physics.py

Fix domain subsetting, SWE melt, docstrings.

---

examples/example_nc.conf
metsim/metsim.py

add out_precision option

---

metsim/io.py
metsim/metsim.py

Add parameter set and variable names to output metadata

---

metsim/disaggregate.py

Adding documentation on longwave calculations

---

metsim/io.py

subtract 12 hours before rounding

---

MANIFEST.in

include license in manifest.in

---

.zenodo.json

Add Zenodo author list

---

docs/index.rst

Update MtClim link to NTSG

---

docs/configuration.rst
metsim/metsim.py

Replace output_prefix with out_prefix (#171)

---

docs/configuration.rst
docs/whats-new.rst
examples/example_constant_vars_ascii.conf
examples/example_constant_vars_bin.conf
examples/example_constant_vars_nc.conf
metsim/cli/ms.py
metsim/metsim.py
metsim/tests/test_metsim.py

Allow for constant fields in MetSim input

---

metsim/cli/ms.py

Fix invert_dict to preserve order

---

docs/index.rst
docs/whats-new.rst
metsim/cli/ms.py

Add --version option

---

metsim/io.py
metsim/metsim.py

Fix for cftime index rounding

---

metsim/disaggregate.py
metsim/metsim.py
metsim/tests/test_metsim.py

Revert "Bugfix/vp backfill"

---

metsim/disaggregate.py
metsim/metsim.py

This pull request will add a configuration option `period_ending` which if set to True will make output compatible with SUMMA.

[WIP] Feature/period ending

---

metsim/disaggregate.py
metsim/metsim.py
metsim/tests/test_metsim.py

This reverts commit 242b097916168ea778f0923564ccf7c3ff685e81.

Revert "Revert "Bugfix/vp backfill""

---

CONTRIBUTING.md
README.md
paper/paper.md

merge master into develop

---

paper/paper.md

Removing duplicate figure labels.

---

paper/paper.md

fixes to paper

---

paper/paper.bib

fixes in bib

---

docs/whats-new.rst
metsim/cli/ms.py
paper/paper.bib

Prepare for 2.2.2 release

---

metsim/disaggregate.py

Fix disaggregate to use correct calendar

---

docs/whats-new.rst
metsim/disaggregate.py
metsim/io.py

Fix minor bugs on dimension naming
